- name: play level var
  hosts: local
  connection: local
  vars:
    COURSE: ansible
    DURATION: 10hrs
    TRINER: ravi
  tasks:
  - name: print cource info
    ansible.builtin.debug:
      msg: "hello {{ COURSE }}, duration {{ DURATION }}, {{ TRINER }}"