- name: Practice file 
  hosts: local
  connection: local
  vars_files: 
  - var.yaml
  tasks:
  - name: print the varibles
    ansible.builtin.debug:
      msg: "{{ COURSE }}, {{ DURATION }}, {{ TRINER }}"
