name: my ansibel file
#host: local
#connection: local host
host: frontend
  task:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enable: yes